"""
Base strategy class that all trading strategies inherit from.
"""
from abc import ABC, abstractmethod
from typing import Dict, List, Optional, Any
from dataclasses import dataclass
from datetime import datetime
from loguru import logger


@dataclass
class Signal:
    """Trading signal generated by a strategy."""
    strategy_name: str
    token_id: str
    market_id: str
    side: str  # "BUY" or "SELL"
    size: float
    price: Optional[float] = None  # None for market orders
    confidence: float = 0.5  # 0-1 confidence score
    reason: str = ""
    timestamp: datetime = None
    
    def __post_init__(self):
        if self.timestamp is None:
            self.timestamp = datetime.now()


@dataclass
class MarketData:
    """Normalized market data for strategies."""
    token_id: str
    market_id: str
    question: str
    best_bid: float
    best_ask: float
    mid_price: float
    volume_24h: float
    liquidity: float
    timestamp: datetime
    extra: Dict[str, Any] = None
    
    def __post_init__(self):
        if self.extra is None:
            self.extra = {}
    
    @property
    def spread(self) -> float:
        """Calculate bid-ask spread."""
        return self.best_ask - self.best_bid
    
    @property
    def spread_pct(self) -> float:
        """Calculate spread as percentage."""
        if self.mid_price > 0:
            return (self.spread / self.mid_price) * 100
        return 0


class BaseStrategy(ABC):
    """Abstract base class for all trading strategies."""
    
    def __init__(self, name: str, config: Dict[str, Any]):
        self.name = name
        self.config = config
        self.enabled = True
        self.last_run = None
        self.signals_generated = 0
        self.trades_executed = 0
        self.pnl = 0.0
        
    @abstractmethod
    def analyze(self, market_data: List[MarketData]) -> List[Signal]:
        """
        Analyze market data and generate trading signals.
        
        Args:
            market_data: List of current market data
            
        Returns:
            List of trading signals
        """
        pass
    
    @abstractmethod
    def get_required_data(self) -> List[str]:
        """
        Return list of required data fields for this strategy.
        
        Returns:
            List of required field names
        """
        pass
    
    def enable(self):
        """Enable the strategy."""
        self.enabled = True
        logger.info(f"Strategy {self.name} enabled")
    
    def disable(self):
        """Disable the strategy."""
        self.enabled = False
        logger.info(f"Strategy {self.name} disabled")
    
    def is_enabled(self) -> bool:
        """Check if strategy is enabled."""
        return self.enabled
    
    def get_stats(self) -> Dict[str, Any]:
        """Get strategy statistics."""
        return {
            "name": self.name,
            "enabled": self.enabled,
            "signals_generated": self.signals_generated,
            "trades_executed": self.trades_executed,
            "pnl": self.pnl,
            "last_run": self.last_run
        }
    
    def update_stats(self, signal_executed: bool = False, pnl: float = 0):
        """Update strategy statistics."""
        self.last_run = datetime.now()
        self.signals_generated += 1
        if signal_executed:
            self.trades_executed += 1
            self.pnl += pnl


class StrategyManager:
    """Manages multiple trading strategies."""
    
    def __init__(self):
        self.strategies: Dict[str, BaseStrategy] = {}
        
    def register(self, strategy: BaseStrategy):
        """Register a strategy."""
        self.strategies[strategy.name] = strategy
        logger.info(f"Registered strategy: {strategy.name}")
        
    def unregister(self, name: str):
        """Unregister a strategy."""
        if name in self.strategies:
            del self.strategies[name]
            logger.info(f"Unregistered strategy: {name}")
            
    def get_strategy(self, name: str) -> Optional[BaseStrategy]:
        """Get a strategy by name."""
        return self.strategies.get(name)
        
    def get_all_strategies(self) -> List[BaseStrategy]:
        """Get all registered strategies."""
        return list(self.strategies.values())
        
    def analyze_all(self, market_data: List[MarketData]) -> List[Signal]:
        """
        Run all enabled strategies and aggregate signals.
        
        Args:
            market_data: Current market data
            
        Returns:
            Combined list of signals from all strategies
        """
        all_signals = []
        
        for strategy in self.strategies.values():
            if strategy.is_enabled():
                try:
                    signals = strategy.analyze(market_data)
                    all_signals.extend(signals)
                except Exception as e:
                    logger.error(f"Error in strategy {strategy.name}: {e}")
                    
        # Sort by confidence (highest first)
        all_signals.sort(key=lambda x: x.confidence, reverse=True)
        
        return all_signals
    
    def get_stats(self) -> Dict[str, Dict]:
        """Get statistics for all strategies."""
        return {name: strategy.get_stats() for name, strategy in self.strategies.items()}
